name: middle_aged_dating
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"



dependencies:
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.2.0
  fluttertoast: ^8.0.9
  page_transition: ^2.0.4


 

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
 
